export const acceptedBranchRequests: string[][] = [
  ["branch"],
  ...["--list", "-l", "--all", "-a", "--remotes", "-r", "--verbose", "-v"].map(
    (flag) => ["branch", flag],
  ),
  ["branch", "--all", "--verbose"],
  ["branch", "--remotes", "-v"],
  ["branch", "--all", "--remotes"],
  ["branch", "--list", "--list"],
  ["branch", "-l", "--list"],
  ["branch", "-a", "--all"],
  ["branch", "-r", "--remotes"],
  ["branch", "-v", "-v"],
  ["branch", "-v", "--verbose"],
  ["branch", "--list", "--"],
  ["branch", "-l", "--"],
  ["branch", "--list", "feature/topic"],
  ["branch", "-l", "feature/*"],
  ["branch", "--list", "feature/to?ic"],
  ["branch", "--list", "feature/[t]opic"],
  ["branch", "--list", "main", "feature/*"],
  ["branch", "--list", "--", "feature/*", "main"],
  ["branch", "--all", "--list", "*"],
  ["branch", "--list", "--all", "--verbose", "--", "*"],
  ["branch", "--remotes", "--list", "origin/*"],
  ["branch", "-r", "-l", "--", "origin/*"],
  ...[
    "missing-branch",
    ".env",
    "../outside",
    "/tmp/outside",
    "C:/outside",
    "escape",
    "dangling",
    "restricted-alias",
    "HEAD:file.txt",
    "space name",
    "日本語*",
    String.raw`a\b`,
  ].map((pattern) => ["branch", "--list", pattern]),
];

export const rejectedBranchRequests: Array<[string[], RegExp]> = [
  [["branch", "new-branch"], /patterns require explicit listing/i],
  [["branch", "feature/topic"], /patterns require explicit listing/i],
  [["branch", "new-branch", "HEAD"], /patterns require explicit listing/i],
  [["branch", "--all", "feature/*"], /patterns require explicit listing/i],
  [["branch", "--remotes", "origin/*"], /patterns require explicit listing/i],
  [["branch", "--verbose", "new-branch"], /patterns require explicit listing/i],
  [["branch", "--"], /separator requires explicit listing/i],
  [["branch", "--", "new-branch"], /separator requires explicit listing/i],
  [
    ["branch", "--all", "--", "feature/*"],
    /separator requires explicit listing/i,
  ],
  [["branch", "--list", "--", "--"], /multiple Git branch separators/i],
  [["branch", "--list", "main", "--"], /unsupported option/i],
  [["branch", "--list", "main", "--", "--"], /multiple Git branch separators/i],
  [["branch", "--list", "main", "--all"], /unsupported option/i],
  [["branch", "--list", "--", "--all"], /unsupported option/i],
  ...[
    "",
    "bad\0name",
    "bad\nname",
    "bad\rname",
    "bad\tname",
    "bad\u001bname",
    "bad\u007fname",
  ].flatMap((pattern) => [
    [["branch", "--list", pattern], /invalid Git branch pattern/i] as [
      string[],
      RegExp,
    ],
    [["branch", "--list", "--", pattern], /invalid Git branch pattern/i] as [
      string[],
      RegExp,
    ],
  ]),
];

const unsupportedForms: string[][] = [
  ["-d", "feature/topic"],
  ["-D", "feature/topic"],
  ["--delete", "feature/topic"],
  ["--delete=feature/topic"],
  ["-m", "feature/topic", "renamed"],
  ["-M", "feature/topic", "renamed"],
  ["--move", "feature/topic", "renamed"],
  ["--move=renamed"],
  ["-c", "feature/topic", "copied"],
  ["-C", "feature/topic", "copied"],
  ["--copy", "feature/topic", "copied"],
  ["--copy=copied"],
  ["-f", "new-branch"],
  ["--force", "new-branch"],
  ["-t", "new-branch"],
  ["--track", "new-branch"],
  ["--track=direct", "new-branch"],
  ["--track=inherit", "new-branch"],
  ["--no-track", "new-branch"],
  ["-u", "origin/main"],
  ["-uorigin/main"],
  ["--set-upstream-to", "origin/main"],
  ["--set-upstream-to=origin/main"],
  ["--set-upstream", "origin/main"],
  ["--unset-upstream"],
  ["--create-reflog", "new-branch"],
  ["--edit-description"],
  ["--recurse-submodules", "new-branch"],
  ["--no-list"],
  ["--no-delete"],
  ["--no-move"],
  ["--no-copy"],
  ["--unknown"],
  ["--lis"],
  ["-al"],
  ["-vv"],
  ["--list=feature/*"],
  ["--all=true"],
  ["--remotes=true"],
  ["--verbose=2"],
  ["--contains", "HEAD"],
  ["--no-contains", "HEAD"],
  ["--merged", "HEAD"],
  ["--no-merged", "HEAD"],
  ["--points-at", "HEAD"],
  ["--show-current"],
  ["--format=%(refname)"],
  ["--sort=refname"],
  ["--column"],
  ["--color=always"],
  ["--ignore-case"],
  ["--abbrev=7"],
  ["--quiet"],
  ["-c", "core.pager=sentinel"],
  ["-ccore.pager=sentinel"],
  ["--config-env", "core.pager=PAGER"],
  ["--config-env=core.pager=PAGER"],
  ["-C", "directory"],
  ["-Cdirectory"],
  ["--git-dir", ".git"],
  ["--git-dir=.git"],
  ["--work-tree", "."],
  ["--work-tree=."],
  ["--paginate"],
  ["--no-pager"],
  ["--literal-pathspecs"],
  ["--bare"],
  ["--skip-env"],
  ["--ultra-compact"],
  ["--spekta-force"],
  ["--spekta-force=true"],
];
for (const form of unsupportedForms) {
  for (const args of [
    ["branch", ...form],
    ["branch", "--list", ...form],
    ["branch", ...form, "--list"],
    ["branch", "--list", "main", ...form],
    ["branch", "--list", "--", ...form],
  ]) {
    rejectedBranchRequests.push([args, /unsupported option/i]);
  }
}
for (const override of [
  ["-c", "core.pager=sentinel"],
  ["-ccore.pager=sentinel"],
  ["--config-env", "core.pager=PAGER"],
  ["--config-env=core.pager=PAGER"],
  ["-C", "directory"],
  ["-Cdirectory"],
  ["--git-dir", ".git"],
  ["--git-dir=.git"],
  ["--work-tree", "."],
  ["--work-tree=."],
  ["--paginate"],
  ["--no-pager"],
  ["--bare"],
]) {
  rejectedBranchRequests.push([
    [...override, "branch"],
    /unsupported Git subcommand/i,
  ]);
}
