import { acceptedBranchRequests } from "./proxy-branch.test-fixtures";

export const realRequests: string[][] = [
  ...acceptedBranchRequests,
  ["status"],
  ["status", "-s"],
  ["status", "--short"],
  ["status", "-b"],
  ["status", "--branch"],
  ["status", "--porcelain"],
  ["status", "--porcelain=v1"],
  ["status", "--porcelain=v2"],
  ["status", "--untracked-files=no"],
  ["status", "--untracked-files=normal"],
  ["status", "--untracked-files=all"],
  ["status", "--short", "--", "file.txt", "space name", "-file"],
  ["status", "--"],
  ["log"],
  ["log", "--oneline"],
  ["log", "--graph"],
  ["log", "--all"],
  ["log", "--decorate"],
  ["log", "--decorate=short"],
  ["log", "--decorate=full"],
  ["log", "--decorate=no"],
  ["log", "-n", "1"],
  ["log", "--max-count=1"],
  ["log", "-p", "-n", "1"],
  ["log", "--patch", "-n", "1"],
  ["log", "--no-patch"],
  ["log", "--stat", "-n", "1"],
  ["log", "--name-only", "-n", "1"],
  ["log", "--name-status", "-n", "1"],
  ["log", "feature/topic"],
  ["log", "refs/heads/main"],
  ["log", "HEAD~1^0"],
  ["log", "main~1..HEAD"],
  ["log", "main~1...HEAD"],
  ["log", "..HEAD"],
  ["log", "HEAD.."],
  ["log", "--oneline", "HEAD", "--", "gone.txt"],
  ["show"],
  ["show", "--oneline"],
  ["show", "-p"],
  ["show", "--patch"],
  ["show", "--no-patch"],
  ["show", "--stat"],
  ["show", "--name-only"],
  ["show", "--name-status"],
  ["show", "HEAD^"],
  ["show", "feature/topic"],
  ["show", "HEAD", "--", "file.txt"],
  ["show", "--", "gone.txt"],
  ["show", "HEAD:file.txt"],
  ["show", "--no-patch", "HEAD:space name"],
  ["show", "HEAD:-file"],
  ["show", "HEAD^:gone.txt"],
  ["diff"],
  ["diff", "--"],
  ["diff", "-p"],
  ["diff", "--patch"],
  ["diff", "--no-patch"],
  ["diff", "--stat"],
  ["diff", "--name-only"],
  ["diff", "--name-status"],
  ["diff", "--cached"],
  ["diff", "--staged"],
  ["diff", "--cached", "HEAD"],
  ["diff", "--staged", "--stat", "HEAD~1"],
  ["diff", "HEAD"],
  ["diff", "HEAD~1^0"],
  ["diff", "feature/topic"],
  ["diff", "refs/heads/main"],
  ["diff", "HEAD~1", "HEAD"],
  ["diff", "HEAD~1..HEAD"],
  ["diff", "HEAD~1...HEAD"],
  ["diff", "--", "space name", "-file"],
  ["diff", "--cached", "--name-status", "--", "other.txt"],
  ["diff", "--staged", "HEAD~1", "--", "other.txt"],
  ["diff", "--stat", "HEAD", "--", "file.txt"],
  ["diff", "HEAD~1", "HEAD", "--", "file.txt"],
  ["diff", "HEAD~1..HEAD", "--", "gone.txt"],
  ["diff", "HEAD~1...HEAD", "--", "file.txt"],
  ["diff", "--", "missing.txt"],
];
