export const unsupportedBranchForms: string[][] = [
  ["-d", "feature/topic"],
  ["-D", "feature/topic"],
  ["--delete", "feature/topic"],
  ["--delete=feature/topic"],
  ["-m", "feature/topic", "renamed"],
  ["-M", "feature/topic", "renamed"],
  ["--move", "feature/topic", "renamed"],
  ["--move=renamed"],
  ["-c", "feature/topic", "copied"],
  ["-C", "feature/topic", "copied"],
  ["--copy", "feature/topic", "copied"],
  ["--copy=copied"],
  ["-f", "new-branch"],
  ["--force", "new-branch"],
  ["-t", "new-branch"],
  ["--track", "new-branch"],
  ["--track=direct", "new-branch"],
  ["--track=inherit", "new-branch"],
  ["--no-track", "new-branch"],
  ["-u", "origin/main"],
  ["-uorigin/main"],
  ["--set-upstream-to", "origin/main"],
  ["--set-upstream-to=origin/main"],
  ["--set-upstream", "origin/main"],
  ["--unset-upstream"],
  ["--create-reflog", "new-branch"],
  ["--edit-description"],
  ["--recurse-submodules", "new-branch"],
  ["--no-list"],
  ["--no-delete"],
  ["--no-move"],
  ["--no-copy"],
  ["--unknown"],
  ["--lis"],
  ["-al"],
  ["-vv"],
  ["--list=feature/*"],
  ["--all=true"],
  ["--remotes=true"],
  ["--verbose=2"],
  ["--contains", "HEAD"],
  ["--no-contains", "HEAD"],
  ["--merged", "HEAD"],
  ["--no-merged", "HEAD"],
  ["--points-at", "HEAD"],
  ["--show-current"],
  ["--format=%(refname)"],
  ["--sort=refname"],
  ["--column"],
  ["--color=always"],
  ["--ignore-case"],
  ["--abbrev=7"],
  ["--quiet"],
  ["-c", "core.pager=sentinel"],
  ["-ccore.pager=sentinel"],
  ["--config-env", "core.pager=PAGER"],
  ["--config-env=core.pager=PAGER"],
  ["-C", "directory"],
  ["-Cdirectory"],
  ["--git-dir", ".git"],
  ["--git-dir=.git"],
  ["--work-tree", "."],
  ["--work-tree=."],
  ["--paginate"],
  ["--no-pager"],
  ["--literal-pathspecs"],
  ["--bare"],
  ["--skip-env"],
  ["--ultra-compact"],
  ["--spekta-force"],
  ["--spekta-force=true"],
];
