export const acceptedBranchRequests: string[][] = [
  ["branch"],
  ...["--list", "-l", "--all", "-a", "--remotes", "-r", "--verbose", "-v"].map(
    (flag) => ["branch", flag],
  ),
  ["branch", "--all", "--verbose"],
  ["branch", "--remotes", "-v"],
  ["branch", "--all", "--remotes"],
  ["branch", "--list", "--list"],
  ["branch", "-l", "--list"],
  ["branch", "-a", "--all"],
  ["branch", "-r", "--remotes"],
  ["branch", "-v", "-v"],
  ["branch", "-v", "--verbose"],
  ["branch", "--list", "--"],
  ["branch", "-l", "--"],
  ["branch", "--list", "feature/topic"],
  ["branch", "-l", "feature/*"],
  ["branch", "--list", "feature/to?ic"],
  ["branch", "--list", "feature/[t]opic"],
  ["branch", "--list", "main", "feature/*"],
  ["branch", "--list", "--", "feature/*", "main"],
  ["branch", "--all", "--list", "*"],
  ["branch", "--list", "--all", "--verbose", "--", "*"],
  ["branch", "--remotes", "--list", "origin/*"],
  ["branch", "-r", "-l", "--", "origin/*"],
  ...[
    "missing-branch",
    ".env",
    "../outside",
    "/tmp/outside",
    "C:/outside",
    "escape",
    "dangling",
    "restricted-alias",
    "HEAD:file.txt",
    "space name",
    "日本語*",
    String.raw`a\b`,
  ].map((pattern) => ["branch", "--list", pattern]),
];
